version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - cdc-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - cdc-network

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9094:9094"    # Porta externa para acesso ao Kafka
    networks:
      - cdc-network

  debezium:
    image: debezium/connect:latest
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=dbz_config
      - OFFSET_STORAGE_TOPIC=dbz_offset
      - BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8083:8083"    # Porta da API REST do Debezium
    networks:
      - cdc-network

networks:
  cdc-network:

volumes:
  sqlserver_data: