version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - cdc-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cdc-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092   # Escuta em todas as interfaces
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Nome do serviço para outros containers
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - cdc-network

  debezium:
    image: debezium/connect:1.9.6.Final
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=dbz_config
      - OFFSET_STORAGE_TOPIC=dbz_offset
      - BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8083:8083"    # Porta da API REST do Debezium
    networks:
      - cdc-network

networks:
  cdc-network:

volumes:
  sqlserver_data: